spring:
    datasource:
      url: jdbc:postsql://localhost:5432/imagelite
      username: postgres
      password: postgres

    jpa:
      database: POSTGRESQL
      hibernate:
        ddl-auto: update
      show-sql: true
